
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TradeHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TradeHistory
 * 
 */
export type TradeHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$TradeHistoryPayload>

export type AggregateTradeHistory = {
  _count: TradeHistoryCountAggregateOutputType | null
  _avg: TradeHistoryAvgAggregateOutputType | null
  _sum: TradeHistorySumAggregateOutputType | null
  _min: TradeHistoryMinAggregateOutputType | null
  _max: TradeHistoryMaxAggregateOutputType | null
}

export type TradeHistoryAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  orderId: number | null
  price: number | null
  quantity: number | null
}

export type TradeHistorySumAggregateOutputType = {
  id: number | null
  userId: number | null
  orderId: number | null
  price: number | null
  quantity: number | null
}

export type TradeHistoryMinAggregateOutputType = {
  id: number | null
  userId: number | null
  orderId: number | null
  symbol: string | null
  type: string | null
  status: string | null
  price: number | null
  quantity: number | null
  executedAt: Date | null
}

export type TradeHistoryMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  orderId: number | null
  symbol: string | null
  type: string | null
  status: string | null
  price: number | null
  quantity: number | null
  executedAt: Date | null
}

export type TradeHistoryCountAggregateOutputType = {
  id: number
  userId: number
  orderId: number
  symbol: number
  type: number
  status: number
  price: number
  quantity: number
  executedAt: number
  _all: number
}


export type TradeHistoryAvgAggregateInputType = {
  id?: true
  userId?: true
  orderId?: true
  price?: true
  quantity?: true
}

export type TradeHistorySumAggregateInputType = {
  id?: true
  userId?: true
  orderId?: true
  price?: true
  quantity?: true
}

export type TradeHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  orderId?: true
  symbol?: true
  type?: true
  status?: true
  price?: true
  quantity?: true
  executedAt?: true
}

export type TradeHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  orderId?: true
  symbol?: true
  type?: true
  status?: true
  price?: true
  quantity?: true
  executedAt?: true
}

export type TradeHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  orderId?: true
  symbol?: true
  type?: true
  status?: true
  price?: true
  quantity?: true
  executedAt?: true
  _all?: true
}

export type TradeHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TradeHistory to aggregate.
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeHistories to fetch.
   */
  orderBy?: Prisma.TradeHistoryOrderByWithRelationInput | Prisma.TradeHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TradeHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TradeHistories
  **/
  _count?: true | TradeHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TradeHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TradeHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TradeHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TradeHistoryMaxAggregateInputType
}

export type GetTradeHistoryAggregateType<T extends TradeHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateTradeHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTradeHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateTradeHistory[P]>
}




export type TradeHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TradeHistoryWhereInput
  orderBy?: Prisma.TradeHistoryOrderByWithAggregationInput | Prisma.TradeHistoryOrderByWithAggregationInput[]
  by: Prisma.TradeHistoryScalarFieldEnum[] | Prisma.TradeHistoryScalarFieldEnum
  having?: Prisma.TradeHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TradeHistoryCountAggregateInputType | true
  _avg?: TradeHistoryAvgAggregateInputType
  _sum?: TradeHistorySumAggregateInputType
  _min?: TradeHistoryMinAggregateInputType
  _max?: TradeHistoryMaxAggregateInputType
}

export type TradeHistoryGroupByOutputType = {
  id: number
  userId: number
  orderId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt: Date
  _count: TradeHistoryCountAggregateOutputType | null
  _avg: TradeHistoryAvgAggregateOutputType | null
  _sum: TradeHistorySumAggregateOutputType | null
  _min: TradeHistoryMinAggregateOutputType | null
  _max: TradeHistoryMaxAggregateOutputType | null
}

export type GetTradeHistoryGroupByPayload<T extends TradeHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TradeHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TradeHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TradeHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TradeHistoryGroupByOutputType[P]>
      }
    >
  >



export type TradeHistoryWhereInput = {
  AND?: Prisma.TradeHistoryWhereInput | Prisma.TradeHistoryWhereInput[]
  OR?: Prisma.TradeHistoryWhereInput[]
  NOT?: Prisma.TradeHistoryWhereInput | Prisma.TradeHistoryWhereInput[]
  id?: Prisma.IntFilter<"TradeHistory"> | number
  userId?: Prisma.IntFilter<"TradeHistory"> | number
  orderId?: Prisma.IntFilter<"TradeHistory"> | number
  symbol?: Prisma.StringFilter<"TradeHistory"> | string
  type?: Prisma.StringFilter<"TradeHistory"> | string
  status?: Prisma.StringFilter<"TradeHistory"> | string
  price?: Prisma.FloatFilter<"TradeHistory"> | number
  quantity?: Prisma.FloatFilter<"TradeHistory"> | number
  executedAt?: Prisma.DateTimeFilter<"TradeHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  order?: Prisma.XOR<Prisma.OrdersScalarRelationFilter, Prisma.OrdersWhereInput>
}

export type TradeHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  order?: Prisma.OrdersOrderByWithRelationInput
}

export type TradeHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TradeHistoryWhereInput | Prisma.TradeHistoryWhereInput[]
  OR?: Prisma.TradeHistoryWhereInput[]
  NOT?: Prisma.TradeHistoryWhereInput | Prisma.TradeHistoryWhereInput[]
  userId?: Prisma.IntFilter<"TradeHistory"> | number
  orderId?: Prisma.IntFilter<"TradeHistory"> | number
  symbol?: Prisma.StringFilter<"TradeHistory"> | string
  type?: Prisma.StringFilter<"TradeHistory"> | string
  status?: Prisma.StringFilter<"TradeHistory"> | string
  price?: Prisma.FloatFilter<"TradeHistory"> | number
  quantity?: Prisma.FloatFilter<"TradeHistory"> | number
  executedAt?: Prisma.DateTimeFilter<"TradeHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  order?: Prisma.XOR<Prisma.OrdersScalarRelationFilter, Prisma.OrdersWhereInput>
}, "id">

export type TradeHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
  _count?: Prisma.TradeHistoryCountOrderByAggregateInput
  _avg?: Prisma.TradeHistoryAvgOrderByAggregateInput
  _max?: Prisma.TradeHistoryMaxOrderByAggregateInput
  _min?: Prisma.TradeHistoryMinOrderByAggregateInput
  _sum?: Prisma.TradeHistorySumOrderByAggregateInput
}

export type TradeHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.TradeHistoryScalarWhereWithAggregatesInput | Prisma.TradeHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.TradeHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TradeHistoryScalarWhereWithAggregatesInput | Prisma.TradeHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TradeHistory"> | number
  userId?: Prisma.IntWithAggregatesFilter<"TradeHistory"> | number
  orderId?: Prisma.IntWithAggregatesFilter<"TradeHistory"> | number
  symbol?: Prisma.StringWithAggregatesFilter<"TradeHistory"> | string
  type?: Prisma.StringWithAggregatesFilter<"TradeHistory"> | string
  status?: Prisma.StringWithAggregatesFilter<"TradeHistory"> | string
  price?: Prisma.FloatWithAggregatesFilter<"TradeHistory"> | number
  quantity?: Prisma.FloatWithAggregatesFilter<"TradeHistory"> | number
  executedAt?: Prisma.DateTimeWithAggregatesFilter<"TradeHistory"> | Date | string
}

export type TradeHistoryCreateInput = {
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTradeHistoryInput
  order: Prisma.OrdersCreateNestedOneWithoutTradeHistoryInput
}

export type TradeHistoryUncheckedCreateInput = {
  id?: number
  userId: number
  orderId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryUpdateInput = {
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTradeHistoryNestedInput
  order?: Prisma.OrdersUpdateOneRequiredWithoutTradeHistoryNestedInput
}

export type TradeHistoryUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryCreateManyInput = {
  id?: number
  userId: number
  orderId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryUpdateManyMutationInput = {
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryListRelationFilter = {
  every?: Prisma.TradeHistoryWhereInput
  some?: Prisma.TradeHistoryWhereInput
  none?: Prisma.TradeHistoryWhereInput
}

export type TradeHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TradeHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
}

export type TradeHistoryAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
}

export type TradeHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
}

export type TradeHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  executedAt?: Prisma.SortOrder
}

export type TradeHistorySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
}

export type TradeHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput> | Prisma.TradeHistoryCreateWithoutUserInput[] | Prisma.TradeHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutUserInput | Prisma.TradeHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TradeHistoryCreateManyUserInputEnvelope
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
}

export type TradeHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput> | Prisma.TradeHistoryCreateWithoutUserInput[] | Prisma.TradeHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutUserInput | Prisma.TradeHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TradeHistoryCreateManyUserInputEnvelope
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
}

export type TradeHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput> | Prisma.TradeHistoryCreateWithoutUserInput[] | Prisma.TradeHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutUserInput | Prisma.TradeHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TradeHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.TradeHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TradeHistoryCreateManyUserInputEnvelope
  set?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  disconnect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  delete?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  update?: Prisma.TradeHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.TradeHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TradeHistoryUpdateManyWithWhereWithoutUserInput | Prisma.TradeHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
}

export type TradeHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput> | Prisma.TradeHistoryCreateWithoutUserInput[] | Prisma.TradeHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutUserInput | Prisma.TradeHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TradeHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.TradeHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TradeHistoryCreateManyUserInputEnvelope
  set?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  disconnect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  delete?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  update?: Prisma.TradeHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.TradeHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TradeHistoryUpdateManyWithWhereWithoutUserInput | Prisma.TradeHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
}

export type TradeHistoryCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput> | Prisma.TradeHistoryCreateWithoutOrderInput[] | Prisma.TradeHistoryUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutOrderInput | Prisma.TradeHistoryCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.TradeHistoryCreateManyOrderInputEnvelope
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
}

export type TradeHistoryUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput> | Prisma.TradeHistoryCreateWithoutOrderInput[] | Prisma.TradeHistoryUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutOrderInput | Prisma.TradeHistoryCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.TradeHistoryCreateManyOrderInputEnvelope
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
}

export type TradeHistoryUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput> | Prisma.TradeHistoryCreateWithoutOrderInput[] | Prisma.TradeHistoryUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutOrderInput | Prisma.TradeHistoryCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.TradeHistoryUpsertWithWhereUniqueWithoutOrderInput | Prisma.TradeHistoryUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.TradeHistoryCreateManyOrderInputEnvelope
  set?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  disconnect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  delete?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  update?: Prisma.TradeHistoryUpdateWithWhereUniqueWithoutOrderInput | Prisma.TradeHistoryUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.TradeHistoryUpdateManyWithWhereWithoutOrderInput | Prisma.TradeHistoryUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
}

export type TradeHistoryUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput> | Prisma.TradeHistoryCreateWithoutOrderInput[] | Prisma.TradeHistoryUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.TradeHistoryCreateOrConnectWithoutOrderInput | Prisma.TradeHistoryCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.TradeHistoryUpsertWithWhereUniqueWithoutOrderInput | Prisma.TradeHistoryUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.TradeHistoryCreateManyOrderInputEnvelope
  set?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  disconnect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  delete?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  connect?: Prisma.TradeHistoryWhereUniqueInput | Prisma.TradeHistoryWhereUniqueInput[]
  update?: Prisma.TradeHistoryUpdateWithWhereUniqueWithoutOrderInput | Prisma.TradeHistoryUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.TradeHistoryUpdateManyWithWhereWithoutOrderInput | Prisma.TradeHistoryUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
}

export type TradeHistoryCreateWithoutUserInput = {
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
  order: Prisma.OrdersCreateNestedOneWithoutTradeHistoryInput
}

export type TradeHistoryUncheckedCreateWithoutUserInput = {
  id?: number
  orderId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput>
}

export type TradeHistoryCreateManyUserInputEnvelope = {
  data: Prisma.TradeHistoryCreateManyUserInput | Prisma.TradeHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TradeHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.TradeHistoryUpdateWithoutUserInput, Prisma.TradeHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TradeHistoryCreateWithoutUserInput, Prisma.TradeHistoryUncheckedCreateWithoutUserInput>
}

export type TradeHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.TradeHistoryUpdateWithoutUserInput, Prisma.TradeHistoryUncheckedUpdateWithoutUserInput>
}

export type TradeHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TradeHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.TradeHistoryUpdateManyMutationInput, Prisma.TradeHistoryUncheckedUpdateManyWithoutUserInput>
}

export type TradeHistoryScalarWhereInput = {
  AND?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
  OR?: Prisma.TradeHistoryScalarWhereInput[]
  NOT?: Prisma.TradeHistoryScalarWhereInput | Prisma.TradeHistoryScalarWhereInput[]
  id?: Prisma.IntFilter<"TradeHistory"> | number
  userId?: Prisma.IntFilter<"TradeHistory"> | number
  orderId?: Prisma.IntFilter<"TradeHistory"> | number
  symbol?: Prisma.StringFilter<"TradeHistory"> | string
  type?: Prisma.StringFilter<"TradeHistory"> | string
  status?: Prisma.StringFilter<"TradeHistory"> | string
  price?: Prisma.FloatFilter<"TradeHistory"> | number
  quantity?: Prisma.FloatFilter<"TradeHistory"> | number
  executedAt?: Prisma.DateTimeFilter<"TradeHistory"> | Date | string
}

export type TradeHistoryCreateWithoutOrderInput = {
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTradeHistoryInput
}

export type TradeHistoryUncheckedCreateWithoutOrderInput = {
  id?: number
  userId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryCreateOrConnectWithoutOrderInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput>
}

export type TradeHistoryCreateManyOrderInputEnvelope = {
  data: Prisma.TradeHistoryCreateManyOrderInput | Prisma.TradeHistoryCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type TradeHistoryUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.TradeHistoryUpdateWithoutOrderInput, Prisma.TradeHistoryUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.TradeHistoryCreateWithoutOrderInput, Prisma.TradeHistoryUncheckedCreateWithoutOrderInput>
}

export type TradeHistoryUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.TradeHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.TradeHistoryUpdateWithoutOrderInput, Prisma.TradeHistoryUncheckedUpdateWithoutOrderInput>
}

export type TradeHistoryUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.TradeHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.TradeHistoryUpdateManyMutationInput, Prisma.TradeHistoryUncheckedUpdateManyWithoutOrderInput>
}

export type TradeHistoryCreateManyUserInput = {
  id?: number
  orderId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryUpdateWithoutUserInput = {
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrdersUpdateOneRequiredWithoutTradeHistoryNestedInput
}

export type TradeHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  orderId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryCreateManyOrderInput = {
  id?: number
  userId: number
  symbol: string
  type: string
  status: string
  price: number
  quantity: number
  executedAt?: Date | string
}

export type TradeHistoryUpdateWithoutOrderInput = {
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTradeHistoryNestedInput
}

export type TradeHistoryUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TradeHistoryUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  quantity?: Prisma.FloatFieldUpdateOperationsInput | number
  executedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TradeHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  orderId?: boolean
  symbol?: boolean
  type?: boolean
  status?: boolean
  price?: boolean
  quantity?: boolean
  executedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeHistory"]>

export type TradeHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  orderId?: boolean
  symbol?: boolean
  type?: boolean
  status?: boolean
  price?: boolean
  quantity?: boolean
  executedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeHistory"]>

export type TradeHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  orderId?: boolean
  symbol?: boolean
  type?: boolean
  status?: boolean
  price?: boolean
  quantity?: boolean
  executedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tradeHistory"]>

export type TradeHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  orderId?: boolean
  symbol?: boolean
  type?: boolean
  status?: boolean
  price?: boolean
  quantity?: boolean
  executedAt?: boolean
}

export type TradeHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "orderId" | "symbol" | "type" | "status" | "price" | "quantity" | "executedAt", ExtArgs["result"]["tradeHistory"]>
export type TradeHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}
export type TradeHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}
export type TradeHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  order?: boolean | Prisma.OrdersDefaultArgs<ExtArgs>
}

export type $TradeHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TradeHistory"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    order: Prisma.$OrdersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    orderId: number
    symbol: string
    type: string
    status: string
    price: number
    quantity: number
    executedAt: Date
  }, ExtArgs["result"]["tradeHistory"]>
  composites: {}
}

export type TradeHistoryGetPayload<S extends boolean | null | undefined | TradeHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload, S>

export type TradeHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TradeHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TradeHistoryCountAggregateInputType | true
  }

export interface TradeHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TradeHistory'], meta: { name: 'TradeHistory' } }
  /**
   * Find zero or one TradeHistory that matches the filter.
   * @param {TradeHistoryFindUniqueArgs} args - Arguments to find a TradeHistory
   * @example
   * // Get one TradeHistory
   * const tradeHistory = await prisma.tradeHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TradeHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, TradeHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TradeHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TradeHistoryFindUniqueOrThrowArgs} args - Arguments to find a TradeHistory
   * @example
   * // Get one TradeHistory
   * const tradeHistory = await prisma.tradeHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TradeHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TradeHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TradeHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryFindFirstArgs} args - Arguments to find a TradeHistory
   * @example
   * // Get one TradeHistory
   * const tradeHistory = await prisma.tradeHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TradeHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, TradeHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TradeHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryFindFirstOrThrowArgs} args - Arguments to find a TradeHistory
   * @example
   * // Get one TradeHistory
   * const tradeHistory = await prisma.tradeHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TradeHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TradeHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TradeHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TradeHistories
   * const tradeHistories = await prisma.tradeHistory.findMany()
   * 
   * // Get first 10 TradeHistories
   * const tradeHistories = await prisma.tradeHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tradeHistoryWithIdOnly = await prisma.tradeHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TradeHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, TradeHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TradeHistory.
   * @param {TradeHistoryCreateArgs} args - Arguments to create a TradeHistory.
   * @example
   * // Create one TradeHistory
   * const TradeHistory = await prisma.tradeHistory.create({
   *   data: {
   *     // ... data to create a TradeHistory
   *   }
   * })
   * 
   */
  create<T extends TradeHistoryCreateArgs>(args: Prisma.SelectSubset<T, TradeHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TradeHistories.
   * @param {TradeHistoryCreateManyArgs} args - Arguments to create many TradeHistories.
   * @example
   * // Create many TradeHistories
   * const tradeHistory = await prisma.tradeHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TradeHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, TradeHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TradeHistories and returns the data saved in the database.
   * @param {TradeHistoryCreateManyAndReturnArgs} args - Arguments to create many TradeHistories.
   * @example
   * // Create many TradeHistories
   * const tradeHistory = await prisma.tradeHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TradeHistories and only return the `id`
   * const tradeHistoryWithIdOnly = await prisma.tradeHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TradeHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TradeHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TradeHistory.
   * @param {TradeHistoryDeleteArgs} args - Arguments to delete one TradeHistory.
   * @example
   * // Delete one TradeHistory
   * const TradeHistory = await prisma.tradeHistory.delete({
   *   where: {
   *     // ... filter to delete one TradeHistory
   *   }
   * })
   * 
   */
  delete<T extends TradeHistoryDeleteArgs>(args: Prisma.SelectSubset<T, TradeHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TradeHistory.
   * @param {TradeHistoryUpdateArgs} args - Arguments to update one TradeHistory.
   * @example
   * // Update one TradeHistory
   * const tradeHistory = await prisma.tradeHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TradeHistoryUpdateArgs>(args: Prisma.SelectSubset<T, TradeHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TradeHistories.
   * @param {TradeHistoryDeleteManyArgs} args - Arguments to filter TradeHistories to delete.
   * @example
   * // Delete a few TradeHistories
   * const { count } = await prisma.tradeHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TradeHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, TradeHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TradeHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TradeHistories
   * const tradeHistory = await prisma.tradeHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TradeHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, TradeHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TradeHistories and returns the data updated in the database.
   * @param {TradeHistoryUpdateManyAndReturnArgs} args - Arguments to update many TradeHistories.
   * @example
   * // Update many TradeHistories
   * const tradeHistory = await prisma.tradeHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TradeHistories and only return the `id`
   * const tradeHistoryWithIdOnly = await prisma.tradeHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TradeHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TradeHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TradeHistory.
   * @param {TradeHistoryUpsertArgs} args - Arguments to update or create a TradeHistory.
   * @example
   * // Update or create a TradeHistory
   * const tradeHistory = await prisma.tradeHistory.upsert({
   *   create: {
   *     // ... data to create a TradeHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TradeHistory we want to update
   *   }
   * })
   */
  upsert<T extends TradeHistoryUpsertArgs>(args: Prisma.SelectSubset<T, TradeHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__TradeHistoryClient<runtime.Types.Result.GetResult<Prisma.$TradeHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TradeHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryCountArgs} args - Arguments to filter TradeHistories to count.
   * @example
   * // Count the number of TradeHistories
   * const count = await prisma.tradeHistory.count({
   *   where: {
   *     // ... the filter for the TradeHistories we want to count
   *   }
   * })
  **/
  count<T extends TradeHistoryCountArgs>(
    args?: Prisma.Subset<T, TradeHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TradeHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TradeHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TradeHistoryAggregateArgs>(args: Prisma.Subset<T, TradeHistoryAggregateArgs>): Prisma.PrismaPromise<GetTradeHistoryAggregateType<T>>

  /**
   * Group by TradeHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TradeHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TradeHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TradeHistoryGroupByArgs['orderBy'] }
      : { orderBy?: TradeHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TradeHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTradeHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TradeHistory model
 */
readonly fields: TradeHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TradeHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TradeHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  order<T extends Prisma.OrdersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrdersDefaultArgs<ExtArgs>>): Prisma.Prisma__OrdersClient<runtime.Types.Result.GetResult<Prisma.$OrdersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TradeHistory model
 */
export interface TradeHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"TradeHistory", 'Int'>
  readonly userId: Prisma.FieldRef<"TradeHistory", 'Int'>
  readonly orderId: Prisma.FieldRef<"TradeHistory", 'Int'>
  readonly symbol: Prisma.FieldRef<"TradeHistory", 'String'>
  readonly type: Prisma.FieldRef<"TradeHistory", 'String'>
  readonly status: Prisma.FieldRef<"TradeHistory", 'String'>
  readonly price: Prisma.FieldRef<"TradeHistory", 'Float'>
  readonly quantity: Prisma.FieldRef<"TradeHistory", 'Float'>
  readonly executedAt: Prisma.FieldRef<"TradeHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TradeHistory findUnique
 */
export type TradeHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TradeHistory to fetch.
   */
  where: Prisma.TradeHistoryWhereUniqueInput
}

/**
 * TradeHistory findUniqueOrThrow
 */
export type TradeHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TradeHistory to fetch.
   */
  where: Prisma.TradeHistoryWhereUniqueInput
}

/**
 * TradeHistory findFirst
 */
export type TradeHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TradeHistory to fetch.
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeHistories to fetch.
   */
  orderBy?: Prisma.TradeHistoryOrderByWithRelationInput | Prisma.TradeHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TradeHistories.
   */
  cursor?: Prisma.TradeHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TradeHistories.
   */
  distinct?: Prisma.TradeHistoryScalarFieldEnum | Prisma.TradeHistoryScalarFieldEnum[]
}

/**
 * TradeHistory findFirstOrThrow
 */
export type TradeHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TradeHistory to fetch.
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeHistories to fetch.
   */
  orderBy?: Prisma.TradeHistoryOrderByWithRelationInput | Prisma.TradeHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TradeHistories.
   */
  cursor?: Prisma.TradeHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TradeHistories.
   */
  distinct?: Prisma.TradeHistoryScalarFieldEnum | Prisma.TradeHistoryScalarFieldEnum[]
}

/**
 * TradeHistory findMany
 */
export type TradeHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter, which TradeHistories to fetch.
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TradeHistories to fetch.
   */
  orderBy?: Prisma.TradeHistoryOrderByWithRelationInput | Prisma.TradeHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TradeHistories.
   */
  cursor?: Prisma.TradeHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TradeHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TradeHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TradeHistories.
   */
  distinct?: Prisma.TradeHistoryScalarFieldEnum | Prisma.TradeHistoryScalarFieldEnum[]
}

/**
 * TradeHistory create
 */
export type TradeHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a TradeHistory.
   */
  data: Prisma.XOR<Prisma.TradeHistoryCreateInput, Prisma.TradeHistoryUncheckedCreateInput>
}

/**
 * TradeHistory createMany
 */
export type TradeHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TradeHistories.
   */
  data: Prisma.TradeHistoryCreateManyInput | Prisma.TradeHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TradeHistory createManyAndReturn
 */
export type TradeHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many TradeHistories.
   */
  data: Prisma.TradeHistoryCreateManyInput | Prisma.TradeHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TradeHistory update
 */
export type TradeHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a TradeHistory.
   */
  data: Prisma.XOR<Prisma.TradeHistoryUpdateInput, Prisma.TradeHistoryUncheckedUpdateInput>
  /**
   * Choose, which TradeHistory to update.
   */
  where: Prisma.TradeHistoryWhereUniqueInput
}

/**
 * TradeHistory updateMany
 */
export type TradeHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TradeHistories.
   */
  data: Prisma.XOR<Prisma.TradeHistoryUpdateManyMutationInput, Prisma.TradeHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TradeHistories to update
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * Limit how many TradeHistories to update.
   */
  limit?: number
}

/**
 * TradeHistory updateManyAndReturn
 */
export type TradeHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * The data used to update TradeHistories.
   */
  data: Prisma.XOR<Prisma.TradeHistoryUpdateManyMutationInput, Prisma.TradeHistoryUncheckedUpdateManyInput>
  /**
   * Filter which TradeHistories to update
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * Limit how many TradeHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TradeHistory upsert
 */
export type TradeHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the TradeHistory to update in case it exists.
   */
  where: Prisma.TradeHistoryWhereUniqueInput
  /**
   * In case the TradeHistory found by the `where` argument doesn't exist, create a new TradeHistory with this data.
   */
  create: Prisma.XOR<Prisma.TradeHistoryCreateInput, Prisma.TradeHistoryUncheckedCreateInput>
  /**
   * In case the TradeHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TradeHistoryUpdateInput, Prisma.TradeHistoryUncheckedUpdateInput>
}

/**
 * TradeHistory delete
 */
export type TradeHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
  /**
   * Filter which TradeHistory to delete.
   */
  where: Prisma.TradeHistoryWhereUniqueInput
}

/**
 * TradeHistory deleteMany
 */
export type TradeHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TradeHistories to delete
   */
  where?: Prisma.TradeHistoryWhereInput
  /**
   * Limit how many TradeHistories to delete.
   */
  limit?: number
}

/**
 * TradeHistory without action
 */
export type TradeHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TradeHistory
   */
  select?: Prisma.TradeHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TradeHistory
   */
  omit?: Prisma.TradeHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TradeHistoryInclude<ExtArgs> | null
}
